sudo: false
language: node_js
node_js:
  - "0.12"

addons:
  firefox: "47.0"

notifications:
  irc:
    channels:
      - "irc.mozilla.org#pageshot"
    on_success: change
    template:
      - "%{message}: %{repository}#%{build_number} (%{branch} - %{commit} : %{author}) %{build_url}"

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 -extension RANDR"

before_script:
  - npm install -g jpm
  - npm install
  - export JPM_FIREFOX_BINARY=`which firefox`
  - firefox -v
  - echo $JPM_FIREFOX_BINARY
  - make all
  - cd ..
  - cd $TRAVIS_BUILD_DIR/

script:
  - pwd && ls && cd $TRAVIS_BUILD_DIR/build/addon && jpm test -v
  - cd $TRAVIS_BUILD_DIR
  - npm run lint
