# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

basepath = "."

locales = [
    "ach",
    "ar",
    "az",
    "be",
    "bg",
    "bn-BD",
    "ca",
    "cs",
    "cy",
    "da",
    "de",
    "dsb",
    "el",
    "en-GB",
    "eo",
    "es-AR",
    "es-CL",
    "es-ES",
    "es-MX",
    "et",
    "fa",
    "fi",
    "fr",
    "fy-NL",
    "ga-IE",
    "gu-IN",
    "he",
    "hi-IN",
    "hr",
    "hsb",
    "hu",
    "hy-AM",
    "id",
    "it",
    "ja",
    "ka",
    "kab",
    "kk",
    "km",
    "ko",
    "lij",
    "lo",
    "lt",
    "mr",
    "ms",
    "my",
    "nb-NO",
    "nl",
    "nn-NO",
    "pa-IN",
    "pl",
    "pt-BR",
    "pt-PT",
    "rm",
    "ro",
    "ru",
    "sk",
    "sl",
    "sq",
    "sr",
    "sv-SE",
    "ta",
    "te",
    "th",
    "tl",
    "tr",
    "uk",
    "ur",
    "uz",
    "vi",
    "zh-CN",
    "zh-TW",
]

[env]
    l = "{l10n_base}/locales/{locale}/"

[[paths]]
    reference = "locales/en-US/**"
    l10n = "{l}**"
